# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master", "development"]
    tags:
      - "*"
  pull_request:
    branches: ["master", "development"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - run: yarn install
        working-directory: ./frontend
      - run: yarn build
        working-directory: ./frontend
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./frontend/dist

  build-and-publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./frontend/dist
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          file: "./Dockerfile"
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/pryvt_ui:${{ github.ref == 'refs/heads/master' && 'latest' || github.ref_name }}
      - name: Build without push
        if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' && !startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          file: "./Dockerfile"
          push: false
